# -*- coding: utf-8 -*-
"""Untitled8.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1hwOS79PfURyses77WXi-byF4hEfeMJGv
"""

# Muhammed Naswih Yasar,12519879
import pandas as pd
import matplotlib.pyplot as plt
df   = pd.read_csv(r'/content/mahindra_and_mahindra_bal.csv', parse_dates=['Year'])
df.sort_values('Year', inplace=True)
plt.plot(df['Year'], df['TotalAssets'],
         marker='o', color='teal')
plt.title('Tata Steel – Total Assets')
plt.xlabel('Year')
plt.ylabel('Total Assets (₹ Cr)')
plt.xticks(rotation=45)
plt.show()

# Muhammed Naswih Yasar,12519879
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
PATH = r'/content/mahindra_and_mahindra_bal.csv'
df   = pd.read_csv(PATH, parse_dates=['Year'])
sns.regplot(x='Borrowing', y='TotalAssets',data=df, color='teal')
plt.title('Borrowings vs Total Assets')
plt.xlabel('Borrowings (₹ Cr)')
plt.ylabel('Total Assets (₹ Cr)')

# Muhammed Naswih Yasar,12519879
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
PATH = r'/content/mahindra_and_mahindra_bal.csv'
df   = pd.read_csv(PATH, parse_dates=['Year'])

sns.histplot(df['Reserves'], kde=True,
             color='steelblue', bins=8)
plt.title('Distribution of Reserves')
plt.xlabel('Reserves (₹ Cr)')
plt.ylabel('Frequency')
plt.show()

# Muhammed Naswih Yasar,12519879
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
PATH = r'/content/mahindra_and_mahindra_bal.csv'
df   = pd.read_csv(PATH, parse_dates=['Year'])

cols = ['FixedAssets', 'Investments']
df_m = df[cols].melt(
    var_name='Type', value_name='Value')
sns.boxplot(x='Type', y='Value',
            data=df_m, palette='Set2')
plt.title('FixedAssets vs Investments')
plt.show()

# Muhammed Naswih Yasar,12519879
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
PATH = r'/content/mahindra_and_mahindra_bal.csv'
df   = pd.read_csv(PATH, parse_dates=['Year'])

df['TAD_Label'] = df['TAD'].map(
    {0: 'Low Deploy', 1: 'High Deploy'})
sns.countplot(x='TAD_Label', data=df,
              palette='coolwarm')
plt.title('Asset Deployment Category Count')
plt.ylabel('Number of Years')
plt.show()

# Muhammed Naswih Yasar,12519879
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np
PATH = r'/content/mahindra_and_mahindra_bal.csv'
df   = pd.read_csv(PATH, parse_dates=['Year'])
x = np.arange(len(df))
plt.bar(x - 0.2, df['EquityCapital'],
        width=0.4, label='Equity')
plt.bar(x + 0.2, df['Reserves'],
        width=0.4, label='Reserves')
plt.xticks(x, df['Year'].dt.year, rotation=45)
plt.title('Equity Capital vs Reserves')
plt.legend(); plt.tight_layout()
plt.show()

# Muhammed Naswih Yasar,12519879
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
PATH = r'/content/mahindra_and_mahindra_bal.csv'
df   = pd.read_csv(PATH, parse_dates=['Year'])

cols = ['FixedAssets','Investments',
        'Borrowing','Reserves',
        'TotalAssets']
sns.heatmap(df[cols].corr(), annot=True,
            cmap='coolwarm', fmt='.2f')
plt.title('Tata Steel – Correlation Heatmap')
plt.show()

# Muhammed Naswih Yasar,12519879
import pandas as pd
import matplotlib.pyplot as plt
PATH = r'/content/mahindra_and_mahindra_bal.csv'
df   = pd.read_csv(PATH, parse_dates=['Year'])
latest = df.iloc[-1]
labels = ['FixedAssets','CWIP',
          'Investments','OtherAssets']
values = [latest[l] for l in labels]
plt.pie(values, labels=labels,
        autopct='%1.1f%%', startangle=140)
plt.title(f'Asset Mix – {latest["Year"].year}')
plt.show()

# Muhammed Naswih Yasar,12519879
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
PATH = r'/content/mahindra_and_mahindra_bal.csv'
df   = pd.read_csv(PATH, parse_dates=['Year'])
df['TAD'] = df['TAD'].astype(str)

sns.lmplot(x='Borrowing',
           y='TotalLiabilities',
           data=df, hue='TAD',
           palette='Set1')
plt.title('Borrowings vs Liabilities by TAD')
plt.show()

# Muhammed Naswih Yasar,12519879
import pandas as pd
import numpy as np
PATH = r'/content/mahindra_and_mahindra_bal.csv'
df   = pd.read_csv(PATH, parse_dates=['Year'])

x = df['Borrowing'].values
y = df['TotalAssets'].values
r = np.corrcoef(x, y)[0, 1]

if r > 0.7:
    print('Debt-driven growth – REVIEW leverage')
elif r > 0.4:
    print('Moderate link – MONITOR borrowings')
else:
    print('Healthy – assets not debt-dependent')
print(f'Correlation = {r:.3f}')

